//! Material 3 color roles.
//!
//! Mappings match androidx `ColorLightTokens` / `ColorDarkTokens` (v0_210):
//! https://m3.material.io/styles/color/roles

use crate::argb::Argb;
use crate::palette;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ColorScheme {
    pub primary: Argb,
    pub on_primary: Argb,
    pub primary_container: Argb,
    pub on_primary_container: Argb,
    pub primary_fixed: Argb,
    pub primary_fixed_dim: Argb,
    pub on_primary_fixed: Argb,
    pub on_primary_fixed_variant: Argb,
    pub secondary: Argb,
    pub on_secondary: Argb,
    pub secondary_container: Argb,
    pub on_secondary_container: Argb,
    pub secondary_fixed: Argb,
    pub secondary_fixed_dim: Argb,
    pub on_secondary_fixed: Argb,
    pub on_secondary_fixed_variant: Argb,
    pub tertiary: Argb,
    pub on_tertiary: Argb,
    pub tertiary_container: Argb,
    pub on_tertiary_container: Argb,
    pub tertiary_fixed: Argb,
    pub tertiary_fixed_dim: Argb,
    pub on_tertiary_fixed: Argb,
    pub on_tertiary_fixed_variant: Argb,
    pub error: Argb,
    pub on_error: Argb,
    pub error_container: Argb,
    pub on_error_container: Argb,
    pub background: Argb,
    pub on_background: Argb,
    pub surface: Argb,
    pub on_surface: Argb,
    pub surface_variant: Argb,
    pub on_surface_variant: Argb,
    pub surface_dim: Argb,
    pub surface_bright: Argb,
    pub surface_container_lowest: Argb,
    pub surface_container_low: Argb,
    pub surface_container: Argb,
    pub surface_container_high: Argb,
    pub surface_container_highest: Argb,
    pub surface_tint: Argb,
    pub outline: Argb,
    pub outline_variant: Argb,
    pub inverse_surface: Argb,
    pub inverse_on_surface: Argb,
    pub inverse_primary: Argb,
    pub scrim: Argb,
    pub shadow: Argb,
}

impl ColorScheme {
    /// Baseline Material You light scheme (purple seed, androidx defaults).
    pub const fn light() -> Self {
        Self {
            primary: palette::PRIMARY.tone40,
            on_primary: palette::PRIMARY.tone100,
            primary_container: palette::PRIMARY.tone90,
            on_primary_container: palette::PRIMARY.tone10,
            primary_fixed: palette::PRIMARY.tone90,
            primary_fixed_dim: palette::PRIMARY.tone80,
            on_primary_fixed: palette::PRIMARY.tone10,
            on_primary_fixed_variant: palette::PRIMARY.tone30,
            secondary: palette::SECONDARY.tone40,
            on_secondary: palette::SECONDARY.tone100,
            secondary_container: palette::SECONDARY.tone90,
            on_secondary_container: palette::SECONDARY.tone10,
            secondary_fixed: palette::SECONDARY.tone90,
            secondary_fixed_dim: palette::SECONDARY.tone80,
            on_secondary_fixed: palette::SECONDARY.tone10,
            on_secondary_fixed_variant: palette::SECONDARY.tone30,
            tertiary: palette::TERTIARY.tone40,
            on_tertiary: palette::TERTIARY.tone100,
            tertiary_container: palette::TERTIARY.tone90,
            on_tertiary_container: palette::TERTIARY.tone10,
            tertiary_fixed: palette::TERTIARY.tone90,
            tertiary_fixed_dim: palette::TERTIARY.tone80,
            on_tertiary_fixed: palette::TERTIARY.tone10,
            on_tertiary_fixed_variant: palette::TERTIARY.tone30,
            error: palette::ERROR.tone40,
            on_error: palette::ERROR.tone100,
            error_container: palette::ERROR.tone90,
            on_error_container: palette::ERROR.tone10,
            background: palette::NEUTRAL.tone98.unwrap(),
            on_background: palette::NEUTRAL.tone10,
            surface: palette::NEUTRAL.tone98.unwrap(),
            on_surface: palette::NEUTRAL.tone10,
            surface_variant: palette::NEUTRAL_VARIANT.tone90,
            on_surface_variant: palette::NEUTRAL_VARIANT.tone30,
            surface_dim: palette::NEUTRAL.tone87.unwrap(),
            surface_bright: palette::NEUTRAL.tone98.unwrap(),
            surface_container_lowest: palette::NEUTRAL.tone100,
            surface_container_low: palette::NEUTRAL.tone96.unwrap(),
            surface_container: palette::NEUTRAL.tone94.unwrap(),
            surface_container_high: palette::NEUTRAL.tone92.unwrap(),
            surface_container_highest: palette::NEUTRAL.tone90,
            surface_tint: palette::PRIMARY.tone40,
            outline: palette::NEUTRAL_VARIANT.tone50,
            outline_variant: palette::NEUTRAL_VARIANT.tone80,
            inverse_surface: palette::NEUTRAL.tone20,
            inverse_on_surface: palette::NEUTRAL.tone95,
            inverse_primary: palette::PRIMARY.tone80,
            scrim: palette::NEUTRAL.tone0,
            shadow: palette::NEUTRAL.tone0,
        }
    }

    /// Baseline Material You dark scheme.
    pub const fn dark() -> Self {
        Self {
            primary: palette::PRIMARY.tone80,
            on_primary: palette::PRIMARY.tone20,
            primary_container: palette::PRIMARY.tone30,
            on_primary_container: palette::PRIMARY.tone90,
            primary_fixed: palette::PRIMARY.tone90,
            primary_fixed_dim: palette::PRIMARY.tone80,
            on_primary_fixed: palette::PRIMARY.tone10,
            on_primary_fixed_variant: palette::PRIMARY.tone30,
            secondary: palette::SECONDARY.tone80,
            on_secondary: palette::SECONDARY.tone20,
            secondary_container: palette::SECONDARY.tone30,
            on_secondary_container: palette::SECONDARY.tone90,
            secondary_fixed: palette::SECONDARY.tone90,
            secondary_fixed_dim: palette::SECONDARY.tone80,
            on_secondary_fixed: palette::SECONDARY.tone10,
            on_secondary_fixed_variant: palette::SECONDARY.tone30,
            tertiary: palette::TERTIARY.tone80,
            on_tertiary: palette::TERTIARY.tone20,
            tertiary_container: palette::TERTIARY.tone30,
            on_tertiary_container: palette::TERTIARY.tone90,
            tertiary_fixed: palette::TERTIARY.tone90,
            tertiary_fixed_dim: palette::TERTIARY.tone80,
            on_tertiary_fixed: palette::TERTIARY.tone10,
            on_tertiary_fixed_variant: palette::TERTIARY.tone30,
            error: palette::ERROR.tone80,
            on_error: palette::ERROR.tone20,
            error_container: palette::ERROR.tone30,
            on_error_container: palette::ERROR.tone90,
            background: palette::NEUTRAL.tone6.unwrap(),
            on_background: palette::NEUTRAL.tone90,
            surface: palette::NEUTRAL.tone6.unwrap(),
            on_surface: palette::NEUTRAL.tone90,
            surface_variant: palette::NEUTRAL_VARIANT.tone30,
            on_surface_variant: palette::NEUTRAL_VARIANT.tone80,
            surface_dim: palette::NEUTRAL.tone6.unwrap(),
            surface_bright: palette::NEUTRAL.tone24.unwrap(),
            surface_container_lowest: palette::NEUTRAL.tone4.unwrap(),
            surface_container_low: palette::NEUTRAL.tone10,
            surface_container: palette::NEUTRAL.tone12.unwrap(),
            surface_container_high: palette::NEUTRAL.tone17.unwrap(),
            surface_container_highest: palette::NEUTRAL.tone22.unwrap(),
            surface_tint: palette::PRIMARY.tone80,
            outline: palette::NEUTRAL_VARIANT.tone60,
            outline_variant: palette::NEUTRAL_VARIANT.tone30,
            inverse_surface: palette::NEUTRAL.tone90,
            inverse_on_surface: palette::NEUTRAL.tone20,
            inverse_primary: palette::PRIMARY.tone40,
            scrim: palette::NEUTRAL.tone0,
            shadow: palette::NEUTRAL.tone0,
        }
    }
}
