[package]
name = "gpui_android"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[lib]
path = "src/gpui_android.rs"

[dependencies]
gpui.workspace = true
anyhow.workspace = true
log.workspace = true
flume.workspace = true
futures.workspace = true
uuid.workspace = true

[target.'cfg(target_os = "android")'.dependencies]
gpui_wgpu.workspace = true
android-activity.workspace = true
ndk.workspace = true
raw-window-handle.workspace = true
jni-sys = "0.4"
